# Generated by Django 3.2.15 on 2022-09-29 14:47

from django.conf import settings
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.RunSQL(
            # Fixes renaming issue due to django "fixing" label name validation
            sql=[("UPDATE django_migrations SET app=%s,applied=now() WHERE app=%s;",
                  ["django_auth", 'django_auth.auth'])],
            reverse_sql=[("DELETE FROM django_migrations WHERE app=%s;", ['django_auth'])],
        )
    ]
