# Generated by Django 3.2.15 on 2022-09-29 15:59

from django.db import connection, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth', '0001_initial'),
    ]

    def rename_table(apps, schema_editor):
        with connection.cursor() as cur:
            cur.execute("SELECT tablename FROM pg_tables WHERE tablename = %s", ['auth_oauth'])
            row = cur.fetchone()
            if not row:
                # There was no auth_oauth table this is a new installation.
                cur.execute("ALTER TABLE auth_oauth_new RENAME TO auth_oauth;")
            else:
                # This is an old installation, the correct table and data already exists so delete the unused stuff.
                cur.execute("DROP TABLE IF EXISTS auth_oauth_new;")
                cur.execute("DELETE FROM django_migrations WHERE app=%s;", ['django_auth.auth'])

    def revert_table(apps, schema_editor):
        with connection.cursor() as cur:
            cur.execute("ALTER TABLE IF EXISTS auth_oauth RENAME TO auth_oauth_new;")

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(rename_table, revert_table)],
            state_operations=[migrations.AlterModelTable(
                name='oauth',
                table='auth_oauth',
            )])
    ]
